---
title: "Class 11 (2-13-18)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

```{r}
# Download some example PDB files
ids <- c("1TND_B","1AGR_A","1TAG_A","1GG2_A","1KJY_A","4G5Q_A")
files <- get.pdb(ids, split = TRUE)
```

```{r}
# Extract and align the chains we are interested in
pdbs <- pdbaln(files, fit = TRUE)
# Print to screen a summary of the 'pdbs' object
pdbs
```

```{r}
# Access the first 5 rows, and 8 columns
pdbs$ali[1:5, 1:8]
```

```{r}
# Associated residues numbers
pdbs$resno[1:5, 1:8]
```

```{r}
# Inspect alignment for gaps
gaps <- gap.inspect(pdbs$ali)
# Indices of non-gap columns
head(gaps$f.inds)
# Access non-gap columns
pdbs$ali[, gaps$f.inds]
```

```{r}
# Calculate sequence identity
seqidentity(pdbs)
# Calculate RMSD
rmsd(pdbs)
# Clustering
hc <- hclust(as.dist(rd))
grps <- cutree(hc, k=3)
# Plot results as dendrogram
hclustplot(hc, k=3)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
